layout_spectrum: 1
typography_spectrum: 0.1021277
color:
  saturation: 0.2070743
  lightness: 0.6589999
  brandStrength: 1
  brandColors:
    - '#0E0C15'
    - '#C6FFFF'
    - '#2FE2E8'
    - '#E980FF'
    - '#B2A430'
  rhythmicContrast: 0.4695866
name: Henry Gordon-Smith
